###################################################################################
# DO NOT EDIT THIS FILE. This is the main script to run Part A of the assignment. #
###################################################################################

# Download the Data if not already downloaded
if [ ! -d "parta/data" ]; then
    echo "Downloading the data for Part A..."
    mkdir -p parta/data
    git clone https://huggingface.co/vsaley/PartADataset
    mv PartADataset/* parta/data/
    rm -rf PartADataset
else
    echo "Data for Part A already exists. Skipping download."
fi

# The directory has folders named case1, case2, ... Get the list of folders
folders=$(ls -d parta/data/case*/)

# Loop through each folder and run the evaluation script
for folder in $folders; do
    echo "Processing $folder..."
    python -m parta.check --config "$folder/config.json" \
        --input-ids "$folder/model_outputs/" \
        --weights "$folder/model_weights.pth"
    echo "Finished processing $folder."
done
