###################################################################################
# DO NOT EDIT THIS FILE. This is the main script to run Part B of the assignment. #
###################################################################################

# You are free to choose default vocab size in the train_tokenizer.py script.

python -m partb.train_tokenizer --input_corpus_path ./data/tokenizer_corpus.txt \
    --output_tokenizer_path ./partb/final_tokenizer/
